version: '3.9'

services:
  prometheus:
    image: prom/prometheus:latest
    user: "0"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - metrics_data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - telegram_bot
      - tg_gifts_worker


  telegram_bot:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - metrics_data:/app/metrics
    ports:
      - "8000:8000"
    restart: on-failure

  backpack_worker:
    build:
      context: .
    env_file:
      - .env
    command: python -u -m src.workers.exchanges.backpack
    volumes:
      - metrics_data:/app/metrics
    ports:
      - "8001:8001"
    restart: on-failure
  
  tg_gifts_worker:
    build:
      context: .
    env_file:
      - .env
    command: python -u -m src.workers.tg_gifts.main
    volumes:
      - metrics_data:/app/metrics
    ports:
      - "8002:8002"
    restart: on-failure

  telegram_portal_worker:
    build:
      context: .
    env_file:
      - .env
    command: python -u -m src.workers.telegram.portal
    volumes:
      - metrics_data:/app/metrics
    ports:
      - "8003:8003"
    

volumes:
  metrics_data:
