version: '3.9'

services:
  metrics_server:
    build:
      context: .
    command: python -m run_metrics_server
    volumes:
      - ./metrics:/app/metrics
    ports:
      - "8000:8000"

  telegram_bot:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - metrics_data:/app/metrics
    environment:
      - PROMETHEUS_MULTIPROC_DIR=/app/metrics

  pool_worker:
    build:
      context: .
    env_file:
      - .env
    command: python -u -m src.pool_runner
    volumes:
      - metrics_data:/app/metrics
    environment:
      - PROMETHEUS_MULTIPROC_DIR=/app/metrics

volumes:
  metrics_data:
