version: '3.9'

services:
  prometheus:
    image: prom/prometheus:latest
    user: "0"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - metrics_data:/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped

  telegram_bot:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - metrics_data:/app/metrics
    ports:
      - "8000:8000"

  backpack_pools:
    build:
      context: .
    env_file:
      - .env
    command: python -u -m src.workers.backpack_pools
    volumes:
      - metrics_data:/app/metrics
    ports:
      - "8001:8001"

volumes:
  metrics_data:
