version: '3.9'

services:
  telegram_bot:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - metrics_data:/app/metrics
    ports:
      - "8000:8000"

  pool_worker:
    build:
      context: .
    env_file:
      - .env
    command: python -u -m src.pool_runner
    volumes:
      - metrics_data:/app/metrics
    ports:
      - "8001:8001"

volumes:
  metrics_data:
