"""fix accounts parents

Revision ID: 024296ef3746
Revises: 5593433b3194
Create Date: 2025-05-04 23:02:09.661784

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "024296ef3746"
down_revision: Union[str, None] = "5593433b3194"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("accounts_parent_id_fkey", "accounts", type_="foreignkey")
    op.create_foreign_key(
        None, "accounts", "accounts", ["parent_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "accounts", type_="foreignkey")
    op.create_foreign_key(
        "accounts_parent_id_fkey", "accounts", "accounts", ["parent_id"], ["id"]
    )
    # ### end Alembic commands ###
