"""Fix fake header

Revision ID: 0b7adf3e5b83
Revises: 7d0004f3e16a
Create Date: 2025-05-04 21:45:31.865900

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0b7adf3e5b83"
down_revision: Union[str, None] = "7d0004f3e16a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
