"""Add ON DELETE CASCADE to pool_account_link.account_id

Revision ID: 3f67fe9a49ac
Revises: 0b7adf3e5b83
Create Date: 2025-05-04 22:49:04.619645

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3f67fe9a49ac"
down_revision: Union[str, None] = "0b7adf3e5b83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "pool_account_link_pool_id_account_id_key", "pool_account_link", type_="unique"
    )
    op.create_unique_constraint(
        "uq_pool_account", "pool_account_link", ["pool_id", "account_id"]
    )
    op.drop_constraint(
        "pool_account_link_account_id_fkey", "pool_account_link", type_="foreignkey"
    )
    op.drop_constraint(
        "pool_account_link_pool_id_fkey", "pool_account_link", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "pool_account_link",
        "accounts",
        ["account_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "pool_account_link", "pools", ["pool_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pool_account_link", type_="foreignkey")
    op.drop_constraint(None, "pool_account_link", type_="foreignkey")
    op.create_foreign_key(
        "pool_account_link_pool_id_fkey",
        "pool_account_link",
        "pools",
        ["pool_id"],
        ["id"],
    )
    op.create_foreign_key(
        "pool_account_link_account_id_fkey",
        "pool_account_link",
        "accounts",
        ["account_id"],
        ["id"],
    )
    op.drop_constraint("uq_pool_account", "pool_account_link", type_="unique")
    op.create_unique_constraint(
        "pool_account_link_pool_id_account_id_key",
        "pool_account_link",
        ["pool_id", "account_id"],
    )
    # ### end Alembic commands ###
