"""simplify pools

Revision ID: 74f7d6babf35
Revises: 3f67fe9a49ac
Create Date: 2025-05-04 22:53:10.223701

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "74f7d6babf35"
down_revision: Union[str, None] = "3f67fe9a49ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "pool_account_link_account_id_fkey", "pool_account_link", type_="foreignkey"
    )
    op.drop_constraint(
        "pool_account_link_pool_id_fkey", "pool_account_link", type_="foreignkey"
    )
    op.create_foreign_key(None, "pool_account_link", "accounts", ["account_id"], ["id"])
    op.create_foreign_key(None, "pool_account_link", "pools", ["pool_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pool_account_link", type_="foreignkey")
    op.drop_constraint(None, "pool_account_link", type_="foreignkey")
    op.create_foreign_key(
        "pool_account_link_pool_id_fkey",
        "pool_account_link",
        "pools",
        ["pool_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "pool_account_link_account_id_fkey",
        "pool_account_link",
        "accounts",
        ["account_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
