"""Refactor Account relationships

Revision ID: b06fd5400e8d
Revises: ea27b97a2532
Create Date: 2025-05-04 21:31:40.948806

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b06fd5400e8d"
down_revision: Union[str, None] = "ea27b97a2532"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "wallet")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts",
        sa.Column("wallet", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
