"""user_friends fk to telegram_id

Revision ID: c89d17569a84
Revises: 7cc4a64b7ae3
Create Date: 2025-05-05 00:37:26.795882

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c89d17569a84"
down_revision: Union[str, None] = "7cc4a64b7ae3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_friends_user_id_fkey", "user_friends", type_="foreignkey")
    op.drop_constraint(
        "user_friends_friend_id_fkey", "user_friends", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "user_friends", "users", ["user_id"], ["telegram_id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "user_friends",
        "users",
        ["friend_id"],
        ["telegram_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_friends", type_="foreignkey")
    op.drop_constraint(None, "user_friends", type_="foreignkey")
    op.create_foreign_key(
        "user_friends_friend_id_fkey",
        "user_friends",
        "users",
        ["friend_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "user_friends_user_id_fkey",
        "user_friends",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
