"""add confirmed field

Revision ID: e7bbb18377ce
Revises: c89d17569a84
Create Date: 2025-05-05 20:58:33.210544

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e7bbb18377ce"
down_revision: Union[str, None] = "c89d17569a84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_friends", sa.Column("confirmed", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_friends", "confirmed")
    # ### end Alembic commands ###
