"""owner_tid

Revision ID: e96a23468ae5
Revises: 1fd1f508f71d
Create Date: 2025-05-04 23:51:23.194515

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e96a23468ae5"
down_revision: Union[str, None] = "1fd1f508f71d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("accounts", sa.Column("owner_tid", sa.Integer(), nullable=False))
    op.create_index(
        op.f("ix_accounts_owner_tid"), "accounts", ["owner_tid"], unique=False
    )
    op.drop_constraint("accounts_owner_id_fkey", "accounts", type_="foreignkey")
    op.drop_column("accounts", "owner_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_friend", "user_friends", type_="unique")
    op.add_column(
        "accounts",
        sa.Column("owner_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "accounts_owner_id_fkey",
        "accounts",
        "users",
        ["owner_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("accounts", "owner_tid")
    # ### end Alembic commands ###
