"""name uniq

Revision ID: ee9024587252
Revises: e7bbb18377ce
Create Date: 2025-05-06 17:08:46.459574

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ee9024587252"
down_revision: Union[str, None] = "e7bbb18377ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "accounts", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "accounts", type_="unique")
    # ### end Alembic commands ###
